name: build-push

on:
  push:
    tags:
      - 'v*' # only build and push tags that start with v

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-oci-images:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install cosign
        uses: sigstore/cosign-installer@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push mcp
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          mcp_image="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
          echo "Building and tagging: $mcp_image:$TAG and $mcp_image:latest"

          docker build -t $mcp_image:$TAG -t $mcp_image:latest .
          docker push $mcp_image:$TAG
          docker push $mcp_image:latest

          # Uncomment if cosign is installed and configured
          cosign sign --yes $mcp_image:$TAG
          cosign sign --yes $mcp_image:latest