name: build-push

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-oci-images:
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            arch: amd64
          - os: ubuntu-24.04-arm
            arch: arm64
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install cosign
        uses: sigstore/cosign-installer@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push mcp
        run: |
          TAG=${{ github.sha }}
          mcp_image="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.arch }}"
          echo "Building and tagging: $mcp_image:$TAG"

          docker build -t $mcp_image:$TAG .
          docker push $mcp_image:$TAG

          # Uncomment if cosign is installed and configured
          cosign sign --yes $mcp_image:$TAG
